apiVersion: "v1"
kind: Pod
metadata:
  name: alpine
  namespace: namespace-psa
  labels:
    name: alpine
    owner: Praparn_L
    version: "1.0"
    module: WebServer
    environment: development
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: alpine
      image: labdocker/alpine:latest
      command: ["sh"]
      resources:
        requests:
          memory: "16Mi"
          cpu: "100m"
        limits:
          memory: "32Mi"
          cpu: "200m"
      ports:
        - containerPort: 22
          protocol: TCP